#   Copyright 2019 Marc Nuri San Felix
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  linux:
    name: Linux Artifact
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: npm install
      - name: Change Package version
        run: ./utils/version-from-tag.js
      - name: Prepare Electron Builder
        run: ./utils/prepare-electron-builder.js
      - name: Build Linux
        run: npm run build:linux
      - name: Upload tar.gz
        run: ./utils/upload-artifact.js electronim-linux-x64.tar.gz application/tar+gzip
      - name: Upload AppImage
        run: ./utils/upload-artifact.js electronim-linux-x86_64.AppImage application/octet-stream
      - name: Publish Snap
        run: |
          sudo apt-get install snapd
          sudo chown root:root / # Snapcraft requires '/' to be root owned
          sudo snap install snapcraft --classic
          echo $SNAPCRAFT_LOGIN | base64 --decode --ignore-garbage > snapcraft.login
          snapcraft login --with snapcraft.login
          snapcraft push --release=stable ./dist/electronim-linux-amd64.snap
  macOS:
    name: macOS Artifact
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: npm install
      - name: Change Package version
        run: ./utils/version-from-tag.js
      - name: Prepare Electron Builder
        run: ./utils/prepare-electron-builder.js
      - name: Build macOS
        run: npm run build:mac
      - name: Upload dmg
        run: ./utils/upload-artifact.js electronim-mac.dmg application/octet-stream
      - name: Upload tar.gz
        run: ./utils/upload-artifact.js electronim-mac.tar.gz application/tar+gzip
